### ISSUE TITLE
RDF Turtle: space between a literal and a language tag should not be tolerated

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/data-validator#8]
Currently, `"test" @en` passes validation, even though it should not.

**Comment by skodapetr** [comment]
Seems like Jena is not capable of reporting the issues, but rdf4j is. 
See [configuration example](https://github.com/datagov-cz/data-validator/blob/main/documentation/example-configurations.md) for information on how to configure rdf4j validator.
